"""init

Revision ID: 673a3a3a3574
Revises: 
Create Date: 2017-07-23 11:51:18.151753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673a3a3a3574'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
